/**
 * SmartKutubxona - Asosiy ma'lumotlar to'plami (O'zbek kitoblari bilan kengaytirilgan)
 * Brauzerda file:// protokoli yoki http:// serverida 100% ishonchli ishlashi uchun
 */
window.SMART_DATA = {
  "categories": [
    {
      "id": "badiiy",
      "name": "Badiiy adabiyot",
      "icon": "fa-book-open",
      "description": "Klassik va zamonaviy o'zbek hamda jahon adabiyoti durdonalari",
      "color": "#10b981",
      "count": 9
    },
    {
      "id": "it",
      "name": "IT va Dasturlash",
      "icon": "fa-code",
      "description": "Dasturlash tillari, tizim arxitekturasi va sun'iy intellekt qo'llanmalari",
      "color": "#3b82f6",
      "count": 5
    },
    {
      "id": "tarix",
      "name": "Tarix",
      "icon": "fa-landmark",
      "description": "O'zbekiston va jahon sivilizatsiyasi, buyuk sarkardalar tarixi",
      "color": "#f59e0b",
      "count": 5
    },
    {
      "id": "ingliz",
      "name": "Ingliz tili",
      "icon": "fa-language",
      "description": "Grammatika, IELTS/TOEFL qo'llanmalari va lug'atlar to'plami",
      "color": "#8b5cf6",
      "count": 4
    },
    {
      "id": "biznes",
      "name": "Biznes va Moliya",
      "icon": "fa-chart-line",
      "description": "Startaplar, boshqaruv, marketing va shaxsiy moliya sirlari",
      "color": "#14b8a6",
      "count": 5
    },
    {
      "id": "ilmfan",
      "name": "Ilm-fan",
      "icon": "fa-atom",
      "description": "Koinot sirlari, fizika, biologiya va ma'naviy-ilmiy meros",
      "color": "#ec4899",
      "count": 4
    }
  ],
  "authors": [
    {
      "id": 1,
      "fullname": "Abdulla Qodiriy",
      "years": "1894 - 1938",
      "image": "https://images.unsplash.com/photo-1544717305-2782549b5136?w=400&auto=format&fit=crop&q=80",
      "bio": "O'zbek romanchiligining asoschisi, atoqli adib, dramaturg va publitsist. Jadidchilik harakatining faol namoyandasi.",
      "booksCount": 2,
      "country": "O'zbekiston"
    },
    {
      "id": 2,
      "fullname": "Robert C. Martin (Uncle Bob)",
      "years": "1952 yilda tug'ilgan",
      "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
      "bio": "Dasturiy injiniring sohasining yetakchi mutaxassisi, Agile manifestining hammuallifi va Clean Code nazariyasi yaratuvchisi.",
      "booksCount": 2,
      "country": "AQSH"
    },
    {
      "id": 3,
      "fullname": "Alisher Navoiy",
      "years": "1441 - 1501",
      "image": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
      "bio": "Buyuk o'zbek shoiri, mutafakkir va davlat arbobi. Turkiy adabiyotning eng yuksak cho'qqisi, 'Xamsa' muallifi.",
      "booksCount": 2,
      "country": "Temuriylar davlati"
    },
    {
      "id": 4,
      "fullname": "James Clear",
      "years": "1986 yilda tug'ilgan",
      "image": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
      "bio": "Amerikalik muallif, odatlar va shaxsiy rivojlanish bo'yicha dunyodagi eng mashhur notiqlardan biri.",
      "booksCount": 1,
      "country": "AQSH"
    },
    {
      "id": 5,
      "fullname": "O'tkir Hoshimov",
      "years": "1941 - 2013",
      "image": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
      "bio": "O'zbekiston xalq yozuvchisi, samimiy va xalqchil nasr ustasi. 'Dunyoning ishlari' va 'Ikki eshik orasi' asarlari muallifi.",
      "booksCount": 2,
      "country": "O'zbekiston"
    },
    {
      "id": 6,
      "fullname": "G'afur G'ulom",
      "years": "1903 - 1966",
      "image": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
      "bio": "O'zbekiston xalq shoiri, akademik va tarjimon. 'Shum bola' qissasi bilan xalq mehrini qozongan so'z san'atkori.",
      "booksCount": 1,
      "country": "O'zbekiston"
    },
    {
      "id": 7,
      "fullname": "Pirimqul Qodirov",
      "years": "1928 - 2010",
      "image": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&auto=format&fit=crop&q=80",
      "bio": "O'zbekiston xalq yozuvchisi, tarixiy romanlar ustasi. Boburiylar sulolasi haqidagi 'Yulduzli tunlar' asari muallifi.",
      "booksCount": 1,
      "country": "O'zbekiston"
    },
    {
      "id": 8,
      "fullname": "Xudoyberdi To'xtaboyev",
      "years": "1932 - 2021",
      "image": "https://images.unsplash.com/photo-1544717305-2782549b5136?w=400&auto=format&fit=crop&q=80",
      "bio": "O'zbekiston xalq yozuvchisi, bolalar adabiyotining yorqin vakili. 'Sariq devni minib' asari ko'plab tillarga tarjima qilingan.",
      "booksCount": 1,
      "country": "O'zbekiston"
    },
    {
      "id": 9,
      "fullname": "Zahiriddin Muhammad Bobur",
      "years": "1483 - 1530",
      "image": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
      "bio": "Buyuk sarkarda, davlat arbobi, shoir va tarixchi. Boburiylar saltanati asoschisi va 'Boburnoma' ensiklopediyasi muallifi.",
      "booksCount": 1,
      "country": "Andijon / Hindiston"
    },
    {
      "id": 10,
      "fullname": "Odil Yoqubov",
      "years": "1926 - 2009",
      "image": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
      "bio": "O'zbekiston xalq yozuvchisi. Mirzo Ulug'bek va Ali Qushchi hayotini aks ettiruvchi 'Ulug'bek xazinasi' tarixiy romani muallifi.",
      "booksCount": 1,
      "country": "O'zbekiston"
    },
    {
      "id": 11,
      "fullname": "Anvar Narzullaev",
      "years": "1988 yilda tug'ilgan",
      "image": "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&auto=format&fit=crop&q=80",
      "bio": "O'zbekistonlik IT mutaxassis, Mohirdev platformasi asoschisi va o'zbek tilidagi Python bo'yicha eng mashhur darsliklar muallifi.",
      "booksCount": 2,
      "country": "O'zbekiston"
    },
    {
      "id": 12,
      "fullname": "Shayx Muhammad Sodiq Muhammad Yusuf",
      "years": "1952 - 2015",
      "image": "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&auto=format&fit=crop&q=80",
      "bio": "Ulug' alloma, Islom olamida tan olingan buyuk olim va mutafakkir. O'zbek xalqiga yuzlab ma'rifiy asarlarni meros qoldirgan.",
      "booksCount": 2,
      "country": "O'zbekiston"
    }
  ],
  "books": [
    {
      "id": 1,
      "title": "O'tkan kunlar",
      "author": "Abdulla Qodiriy",
      "author_id": 1,
      "category": "Badiiy adabiyot",
      "categoryId": "badiiy",
      "year": 1926,
      "pages": 380,
      "language": "O'zbekcha",
      "rating": 4.9,
      "reviews_count": 1840,
      "image": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&auto=format&fit=crop&q=80",
      "description": "O'zbek adabiyotidagi birinchi realistik roman. XIX asr o'rtalaridagi Qo'qon xonligi davridagi ijtimoiy-siyosiy ziddiyatlar, xalq hayoti hamda Otabek va Kumushbibining pokiza muhabbat fojiasi teran falsafiy ruhda tasvirlangan.",
      "featured": true,
      "isNew": false,
      "isbn": "978-9943-01-203-1"
    },
    {
      "id": 2,
      "title": "Clean Code: Toza Kod San'ati",
      "author": "Robert C. Martin",
      "author_id": 2,
      "category": "IT va Dasturlash",
      "categoryId": "it",
      "year": 2008,
      "pages": 464,
      "language": "Inglizcha",
      "rating": 4.8,
      "reviews_count": 2150,
      "image": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=500&auto=format&fit=crop&q=80",
      "description": "Har bir professional dasturchi o'qishi shart bo'lgan fundamental qo'llanma. Kodni qanday toza, tushunarli, qayta ishlatiladigan va mustahkam yozish usullarini amaliy misollar bilan ko'rsatib beradi.",
      "featured": true,
      "isNew": false,
      "isbn": "978-0132350884"
    },
    {
      "id": 3,
      "title": "Atom Odatlar (Atomic Habits)",
      "author": "James Clear",
      "author_id": 4,
      "category": "Biznes va Moliya",
      "categoryId": "biznes",
      "year": 2018,
      "pages": 320,
      "language": "O'zbekcha",
      "rating": 4.9,
      "reviews_count": 3400,
      "image": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=500&auto=format&fit=crop&q=80",
      "description": "Kichik o'zgarishlar qanday qilib hayratlanarli natijalarga olib kelishi haqida jahon bestsalleri. Yomon odatlardan qutulish va yaxshi odatlarni mustahkamlashning ilmiy asoslangan 4 qonuni bayon qilingan.",
      "featured": true,
      "isNew": true,
      "isbn": "978-0735211292"
    },
    {
      "id": 4,
      "title": "Xamsa (Besh doston)",
      "author": "Alisher Navoiy",
      "author_id": 3,
      "category": "Badiiy adabiyot",
      "categoryId": "badiiy",
      "year": 1485,
      "pages": 640,
      "language": "O'zbekcha",
      "rating": 5.0,
      "reviews_count": 4200,
      "image": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&auto=format&fit=crop&q=80",
      "description": "Turkiy adabiyotning tengsiz cho'qqisi. 'Hayrat ul-abror', 'Farhod va Shirin', 'Layli va Majnun', 'Sab'ai sayyor' va 'Saddi Iskandariy' dostonlarini o'z ichiga olgan umumbashariy qadriyatlar ensiklopediyasi.",
      "featured": true,
      "isNew": false,
      "isbn": "978-9943-27-010-3"
    },
    {
      "id": 5,
      "title": "English Grammar in Use",
      "author": "Raymond Murphy",
      "author_id": 2,
      "category": "Ingliz tili",
      "categoryId": "ingliz",
      "year": 2019,
      "pages": 380,
      "language": "Inglizcha",
      "rating": 4.9,
      "reviews_count": 5100,
      "image": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=500&auto=format&fit=crop&q=80",
      "description": "O'rta darajadagi (Intermediate) ingliz tili o'rganuvchilari uchun jahondagi eng mashhur va qulay grammatika qo'llanmasi. Tushunarli qoidalar va boy amaliy mashqlar.",
      "featured": true,
      "isNew": false,
      "isbn": "978-1108457651"
    },
    {
      "id": 6,
      "title": "Vaqtning Qisqacha Tarixi",
      "author": "Stiven Xoking",
      "author_id": 12,
      "category": "Ilm-fan",
      "categoryId": "ilmfan",
      "year": 1988,
      "pages": 256,
      "language": "O'zbekcha",
      "rating": 4.8,
      "reviews_count": 1670,
      "image": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&auto=format&fit=crop&q=80",
      "description": "Koinotning paydo bo'lishi, Katta portlash, qora tuynuklar va vaqt tabiati haqida oddiy va jonli tilda yozilgan jahon ilmiy-ommabop adabiyoti klassikasi.",
      "featured": true,
      "isNew": false,
      "isbn": "978-0553380163"
    },
    {
      "id": 7,
      "title": "Mehrobdan Chayon",
      "author": "Abdulla Qodiriy",
      "author_id": 1,
      "category": "Badiiy adabiyot",
      "categoryId": "badiiy",
      "year": 1928,
      "pages": 320,
      "language": "O'zbekcha",
      "rating": 4.8,
      "reviews_count": 1390,
      "image": "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=500&auto=format&fit=crop&q=80",
      "description": "XIX asr oxiridagi Xudoyorxon saroyidagi fitnalar, xalqning adolatsizlikka qarshi noroziligi hamda Anvar va Ra'noning fidokorona sevgisi tasvirlangan nodir asar.",
      "featured": false,
      "isNew": false,
      "isbn": "978-9943-01-204-8"
    },
    {
      "id": 8,
      "title": "Kecha va Kunduz",
      "author": "Abdulhamid Cho'lpon",
      "author_id": 1,
      "category": "Badiiy adabiyot",
      "categoryId": "badiiy",
      "year": 1936,
      "pages": 304,
      "language": "O'zbekcha",
      "rating": 4.9,
      "reviews_count": 1920,
      "image": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=500&auto=format&fit=crop&q=80",
      "description": "O'zbek ayolining o'tmishdagi ayanchli qismati, jaholat va mustamlaka zulmiga qarshi uyg'onish nafasi ifodalangan shoh asar. Zebi obrazining nozik ruhiy kechinmalari.",
      "featured": true,
      "isNew": false,
      "isbn": "978-9943-27-025-7"
    },
    {
      "id": 9,
      "title": "Temur Tuzuklari",
      "author": "Amir Temur",
      "author_id": 3,
      "category": "Tarix",
      "categoryId": "tarix",
      "year": 1400,
      "pages": 240,
      "language": "O'zbekcha",
      "rating": 5.0,
      "reviews_count": 2890,
      "image": "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=500&auto=format&fit=crop&q=80",
      "description": "Sohibqiron Amir Temurning davlatni boshqarish, harbiy san'at, vazirlar va lashkarboshilarni tanlash, adolatli qonunlar o'rnatish haqidagi qimmatli o'gitlari va qonun-qoidalari.",
      "featured": true,
      "isNew": false,
      "isbn": "978-9943-00-112-5"
    },
    {
      "id": 10,
      "title": "Dunyoning Ishlari",
      "author": "O'tkir Hoshimov",
      "author_id": 5,
      "category": "Badiiy adabiyot",
      "categoryId": "badiiy",
      "year": 1982,
      "pages": 288,
      "language": "O'zbekcha",
      "rating": 5.0,
      "reviews_count": 3200,
      "image": "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=500&auto=format&fit=crop&q=80",
      "description": "Onaga bo'lgan samimiy va cheksiz mehr, insoniylik, mehr-oqibat va hayot saboqlari aks ettirilgan har bir o'zbek xonadonining sevimli qissasi.",
      "featured": true,
      "isNew": true,
      "isbn": "978-9943-28-115-4"
    },
    {
      "id": 11,
      "title": "Ikki Eshik Orasi",
      "author": "O'tkir Hoshimov",
      "author_id": 5,
      "category": "Badiiy adabiyot",
      "categoryId": "badiiy",
      "year": 1986,
      "pages": 448,
      "language": "O'zbekcha",
      "rating": 4.9,
      "reviews_count": 2850,
      "image": "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=500&auto=format&fit=crop&q=80",
      "description": "Ikkinchi jahon urushi yillaridagi xalqimizning jasorati, fidoiyligi, qiyinchiliklar va insoniy fojialar teran tasvirlangan epik roman.",
      "featured": false,
      "isNew": false,
      "isbn": "978-9943-28-116-1"
    },
    {
      "id": 12,
      "title": "Shum Bola",
      "author": "G'afur G'ulom",
      "author_id": 6,
      "category": "Badiiy adabiyot",
      "categoryId": "badiiy",
      "year": 1936,
      "pages": 224,
      "language": "O'zbekcha",
      "rating": 4.9,
      "reviews_count": 3100,
      "image": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&auto=format&fit=crop&q=80",
      "description": "Sho'x, ziyrak va topqir o'zbek bolasining boshidan kechirgan qiziqarli sarguzashtlari orqali o'tmishdagi xalq turmushi hazil va yumor bilan ochib berilgan.",
      "featured": true,
      "isNew": false,
      "isbn": "978-9943-01-312-0"
    },
    {
      "id": 13,
      "title": "Yulduzli Tunlar (Bobur)",
      "author": "Pirimqul Qodirov",
      "author_id": 7,
      "category": "Tarix",
      "categoryId": "tarix",
      "year": 1978,
      "pages": 520,
      "language": "O'zbekcha",
      "rating": 5.0,
      "reviews_count": 4150,
      "image": "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=500&auto=format&fit=crop&q=80",
      "description": "Zahiriddin Muhammad Boburning Farg'onadan to Hindistongacha bo'lgan mashaqqatli hayot yo'li, Vatan sog'inchi va buyuk davlat barpo etishi tasvirlangan durdona tarixiy roman.",
      "featured": true,
      "isNew": false,
      "isbn": "978-9943-27-140-7"
    },
    {
      "id": 14,
      "title": "Sariq Devni Minib",
      "author": "Xudoyberdi To'xtaboyev",
      "author_id": 8,
      "category": "Badiiy adabiyot",
      "categoryId": "badiiy",
      "year": 1968,
      "pages": 280,
      "language": "O'zbekcha",
      "rating": 4.9,
      "reviews_count": 2780,
      "image": "https://images.unsplash.com/photo-1507842229450-78210532645b?w=500&auto=format&fit=crop&q=80",
      "description": "Hoshimjonning sehrli shlyapa topib olib qilgan ajoyib sayohatlari va maktabdagi qiziq hangomalari. O'zbek bolalar adabiyotining eng ko'p o'qilgan kitobi.",
      "featured": false,
      "isNew": false,
      "isbn": "978-9943-01-440-0"
    },
    {
      "id": 15,
      "title": "Boburnoma",
      "author": "Zahiriddin Muhammad Bobur",
      "author_id": 9,
      "category": "Tarix",
      "categoryId": "tarix",
      "year": 1528,
      "pages": 496,
      "language": "O'zbekcha",
      "rating": 4.9,
      "reviews_count": 2600,
      "image": "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=500&auto=format&fit=crop&q=80",
      "description": "Dunyo adabiyotining eng qimmatli tarixiy-memuar durdonasi. Unda O'rta Osiyo, Afg'oniston va Hindistonning tabiati, xalqlari, tili va geografiyasi jonli tilda yoritilgan.",
      "featured": false,
      "isNew": false,
      "isbn": "978-9943-00-514-7"
    },
    {
      "id": 16,
      "title": "Ulug'bek Xazinasi",
      "author": "Odil Yoqubov",
      "author_id": 10,
      "category": "Tarix",
      "categoryId": "tarix",
      "year": 1973,
      "pages": 368,
      "language": "O'zbekcha",
      "rating": 4.8,
      "reviews_count": 2340,
      "image": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=500&auto=format&fit=crop&q=80",
      "description": "Temuriylar davri Samarqandi, Mirzo Ulug'bek rasadxonasi va uning shogirdlari Ali Qushchi bilan birgalikdagi ilmiy jasorati hamda fojiali qismati gavdalantirilgan roman.",
      "featured": false,
      "isNew": false,
      "isbn": "978-9943-27-205-3"
    },
    {
      "id": 17,
      "title": "Python Asoslari: Dasturlashni Noldan O'rganish",
      "author": "Anvar Narzullaev",
      "author_id": 11,
      "category": "IT va Dasturlash",
      "categoryId": "it",
      "year": 2021,
      "pages": 384,
      "language": "O'zbekcha",
      "rating": 4.9,
      "reviews_count": 3800,
      "image": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=500&auto=format&fit=crop&q=80",
      "description": "O'zbek tilida Python dasturlash tilini noldan professional darajagacha o'rganish uchun eng mashhur qo'llanma. Amaliy misollar, mashqlar va testlar bilan boyitilgan.",
      "featured": true,
      "isNew": true,
      "isbn": "978-9943-75-010-4"
    },
    {
      "id": 18,
      "title": "Algoritmlar va Ma'lumotlar Tuzilmasi (O'zbekcha)",
      "author": "Anvar Narzullaev",
      "author_id": 11,
      "category": "IT va Dasturlash",
      "categoryId": "it",
      "year": 2022,
      "pages": 320,
      "language": "O'zbekcha",
      "rating": 4.9,
      "reviews_count": 2100,
      "image": "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=500&auto=format&fit=crop&q=80",
      "description": "IT suhbatlaridan muvaffaqiyatli o'tish uchun zarur bo'lgan algoritmlar: qidiruv, saralash, dinamik dasturlash va graflar o'zbek tilida sodda tilda tushuntirilgan.",
      "featured": false,
      "isNew": true,
      "isbn": "978-9943-75-012-8"
    },
    {
      "id": 19,
      "title": "Ijtimoiy Odoblar",
      "author": "Shayx Muhammad Sodiq Muhammad Yusuf",
      "author_id": 12,
      "category": "Ilm-fan",
      "categoryId": "ilmfan",
      "year": 2012,
      "pages": 448,
      "language": "O'zbekcha",
      "rating": 5.0,
      "reviews_count": 4800,
      "image": "https://images.unsplash.com/photo-1544717305-2782549b5136?w=500&auto=format&fit=crop&q=80",
      "description": "Jamiyatda yashash madaniyati, o'zaro muomala, oila va do'stlik munosabatlarining ma'naviy-axloqiy qoidalari haqida qimmatbaho qo'llanma.",
      "featured": true,
      "isNew": false,
      "isbn": "978-9943-39-012-3"
    },
    {
      "id": 20,
      "title": "Ruhiy Tarbiya (3 jildlik)",
      "author": "Shayx Muhammad Sodiq Muhammad Yusuf",
      "author_id": 12,
      "category": "Ilm-fan",
      "categoryId": "ilmfan",
      "year": 2010,
      "pages": 620,
      "language": "O'zbekcha",
      "rating": 5.0,
      "reviews_count": 3900,
      "image": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&auto=format&fit=crop&q=80",
      "description": "Inson qalbini poklash, nafs tarbiyasi, axloqni go'zallashtirish va ruhiy xotirjamlikka erishish sirlari bayon etilgan fundamental ma'naviy asar.",
      "featured": false,
      "isNew": false,
      "isbn": "978-9943-39-005-5"
    },
    {
      "id": 21,
      "title": "Boy Ota, Kambag'al Ota (O'zbek tilida)",
      "author": "Robert Kiyosaki",
      "author_id": 4,
      "category": "Biznes va Moliya",
      "categoryId": "biznes",
      "year": 1997,
      "pages": 336,
      "language": "O'zbekcha",
      "rating": 4.8,
      "reviews_count": 4100,
      "image": "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=500&auto=format&fit=crop&q=80",
      "description": "Moliyaviy erkinlikka erishish, aktivlar to'plash va pulni to'g'ri boshqarish bo'yicha dunyodagi eng ommabop kitobning to'liq o'zbekcha nashri.",
      "featured": false,
      "isNew": false,
      "isbn": "978-1612680194"
    },
    {
      "id": 22,
      "title": "Noldan Birga (Zero to One o'zbek tilida)",
      "author": "Peter Thiel",
      "author_id": 4,
      "category": "Biznes va Moliya",
      "categoryId": "biznes",
      "year": 2014,
      "pages": 224,
      "language": "O'zbekcha",
      "rating": 4.7,
      "reviews_count": 2480,
      "image": "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=500&auto=format&fit=crop&q=80",
      "description": "Kremniy vodiysi startaplarining sirlari: raqobat emas, yangi bozorlar yaratish falsafasi o'zbek tilida.",
      "featured": false,
      "isNew": true,
      "isbn": "978-0804139298"
    },
    {
      "id": 23,
      "title": "Muvaffaqiyat Kaliti: O'ziga Ishonch Hosil Qilish",
      "author": "Deyl Karnegi",
      "author_id": 4,
      "category": "Biznes va Moliya",
      "categoryId": "biznes",
      "year": 2015,
      "pages": 310,
      "language": "O'zbekcha",
      "rating": 4.8,
      "reviews_count": 3150,
      "image": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=500&auto=format&fit=crop&q=80",
      "description": "Notiqlik san'ati, odamlarni o'ziga jalb qilish va omma oldida hayajonlanmasdan so'zlash bo'yicha klassik amaliy qo'llanma.",
      "featured": false,
      "isNew": false,
      "isbn": "978-9943-34-118-9"
    },
    {
      "id": 24,
      "title": "IELTS 7.5+ O'zbek Tili Yo'riqnomasi",
      "author": "Jamshid Qodirov",
      "author_id": 11,
      "category": "Ingliz tili",
      "categoryId": "ingliz",
      "year": 2023,
      "pages": 290,
      "language": "O'zbekcha",
      "rating": 4.9,
      "reviews_count": 3450,
      "image": "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=500&auto=format&fit=crop&q=80",
      "description": "O'zbek talabalari uchun IELTS Writing va Speaking bosqichlaridan yuqori ball olish sirlari, shablonlar va lug'atlar to'plami.",
      "featured": true,
      "isNew": true,
      "isbn": "978-9943-88-022-1"
    }
  ]
};

/**
 * Ma'lumotlarni xavfsiz olish funksiyasi
 */
async function getSmartData() {
  try {
    const res = await fetch('data/books.json');
    if (res.ok) {
      const data = await res.json();
      return data;
    }
  } catch (e) {
    console.info('Mahalliy SMART_DATA ma\'lumotlaridan foydalanilmoqda');
  }
  return window.SMART_DATA;
}
